import { useState, useEffect, useMemo } from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { analysisBundleFingerprint, loadAnalysisBundle } from '../lib/sessionKeys'
import { postExportPdf } from '../lib/api'
import { getCachedAppealLetter, getCachedAssumptions } from '../lib/outputsCache'

/** Maps to AppealLetterRequest.patient_info — backend uses name, address, phone, email */
function buildPatientInfo(claim: Record<string, unknown>): Record<string, string> {
  const pp = (claim.patient_provider ?? {}) as Record<string, unknown>
  const ar = (claim.appeal_rights ?? {}) as Record<string, unknown>
  const out: Record<string, string> = {}
  const name = typeof pp.patient_full_name === 'string' ? pp.patient_full_name.trim() : ''
  if (name) out.name = name
  const addr = typeof pp.facility_address === 'string' ? pp.facility_address.trim() : ''
  if (addr) out.address = addr
  const phone =
    typeof ar.insurer_appeals_phone === 'string' ? ar.insurer_appeals_phone.trim() : ''
  if (phone) out.phone = phone
  return out
}

const tabs = ['Appeal Letter (Draft)', 'Message to Provider', 'Message to Insurer']

const NO_SESSION_MSG =
  'Complete a claim analysis on /analyze first. Letters are generated by the backend from your claim object and regulatory enrichment — not from static templates.'

const actionItems = [
  { label: 'Finalize Member ID in header', done: false },
  { label: 'Download PDF Draft', done: true },
  { label: 'Attach Physician Statement', done: false },
  { label: 'Mail via Certified Delivery', done: false },
]

export default function AppealDrafting() {
  const [activeTab, setActiveTab] = useState(0)
  const [items, setItems] = useState(actionItems)
  const bundleFingerprint = analysisBundleFingerprint()
  const bundle = useMemo(() => loadAnalysisBundle(), [bundleFingerprint])
  const [drafts, setDrafts] = useState<[string, string, string]>(['', '', ''])
  const [draftLoading, setDraftLoading] = useState(false)
  const [assumptionsState, setAssumptionsState] = useState<{
    loading: boolean
    error: string | null
    reliability_note: string
    overall_confidence_percentage: string
    items: Array<{
      assumption: string
      confidence_percentage: string
      impact: string
      how_to_verify: string
      if_incorrect: string
    }>
  }>({ loading: false, error: null, reliability_note: '', overall_confidence_percentage: '', items: [] })

  const stateRules = bundle?.enrichment?.state_rules as Record<string, unknown> | undefined
  const doiBlock = stateRules?.doi_contact as Record<string, string> | undefined

  useEffect(() => {
    if (!bundle) {
      setAssumptionsState({ loading: false, error: null, reliability_note: '', overall_confidence_percentage: '', items: [] })
      setDrafts([NO_SESSION_MSG, NO_SESSION_MSG, NO_SESSION_MSG])
      return
    }
    setAssumptionsState(s => ({ ...s, loading: true, error: null }))
    getCachedAssumptions(bundle.claim_object, bundle.analysis, bundle.enrichment)
      .then(res => {
        setAssumptionsState({
          loading: false,
          error: null,
          reliability_note: res.reliability_note ?? '',
          overall_confidence_percentage: res.overall_confidence_percentage ?? '',
          items: Array.isArray(res.assumptions) ? res.assumptions : [],
        })
      })
      .catch(() => {
        setAssumptionsState({
          loading: false,
          error: 'Could not load assumptions panel. Ensure the backend is running.',
          reliability_note: '',
          overall_confidence_percentage: '',
          items: [],
        })
      })

    setDraftLoading(true)
    const patientInfo = buildPatientInfo(bundle.claim_object)
    getCachedAppealLetter(bundle.claim_object, bundle.analysis, bundle.enrichment, patientInfo)
      .then(r => {
        setDrafts([
          typeof r.appeal_letter === 'string' && r.appeal_letter.trim()
            ? r.appeal_letter
            : 'The output agent did not return an appeal letter. Check GROQ_API_KEY (or GEMINI_API_KEY) and backend logs.',
          typeof r.provider_message === 'string' && r.provider_message.trim()
            ? r.provider_message
            : 'No provider message returned.',
          typeof r.insurer_message === 'string' && r.insurer_message.trim()
            ? r.insurer_message
            : 'No insurer message returned.',
        ])
      })
      .catch(() => {
        setDrafts([
          'Could not reach the appeal-letter API. Ensure the backend is running and configured.',
          '',
          '',
        ])
      })
      .finally(() => setDraftLoading(false))
  }, [bundle, bundleFingerprint])

  function impactBadgeClass(impact: string) {
    if (impact === 'high') return 'bg-error-container text-on-error-container'
    if (impact === 'medium') return 'bg-tertiary-container text-on-tertiary-container'
    return 'bg-surface-container-high text-on-surface-variant'
  }

  async function exportPdf() {
    const content = drafts[activeTab]
    try {
      const blob = await postExportPdf({ content, format: 'appeal_letter', title: 'Appeal draft' })
      const a = document.createElement('a')
      a.href = URL.createObjectURL(blob)
      a.download = 'appeal-draft.pdf'
      a.click()
      URL.revokeObjectURL(a.href)
    } catch {
      /* silent */
    }
  }

  function downloadTxt() {
    const blob = new Blob([drafts[activeTab]], { type: 'text/plain;charset=utf-8' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = 'appeal-draft.txt'
    a.click()
    URL.revokeObjectURL(a.href)
  }

  function copyDraft() {
    void navigator.clipboard.writeText(drafts[activeTab])
  }

  return (
    <div className="bg-background text-on-background selection:bg-secondary-container min-h-screen flex flex-col">
      <Navbar />

      <main className="pt-24 pb-12">
        {/* Warning Banner */}
        <div className="mx-8 mb-8">
          <div className="bg-tertiary-fixed text-on-tertiary-fixed p-4 rounded-xl flex items-center gap-3 shadow-sm">
            <span className="material-symbols-outlined text-on-tertiary-fixed-variant">warning</span>
            <span className="font-medium">
              Draft only—edit and verify. This content is AI-generated based on provided documents and Indiana regulations. Professional review is required.
            </span>
          </div>
        </div>

        <div className="editorial-margin">
          <header className="mb-12">
            <h1 className="text-4xl md:text-5xl font-extrabold font-headline text-primary tracking-tight mb-2">
              Appeal Drafting Room
            </h1>
            <p className="max-w-2xl leading-relaxed text-on-surface-variant">
              Drafts are produced by the output agent from your analyzed claim. Edit before sending; this is not legal advice.
            </p>
          </header>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* Main Editor */}
            <div className="lg:col-span-8 space-y-6">
              {/* Tabs */}
              <div className="bg-surface-container-low rounded-xl p-1 flex gap-1">
                {tabs.map((tab, i) => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(i)}
                    className={`flex-1 py-3 px-4 rounded-lg text-sm font-semibold transition-all ${activeTab === i ? 'bg-surface-container-lowest text-primary shadow-sm' : 'text-on-surface-variant hover:bg-surface-container-high'}`}
                  >
                    {tab}
                  </button>
                ))}
              </div>

              {/* Editor Canvas */}
              <div className="bg-surface-container-lowest rounded-xl shadow-sm border border-outline-variant/10 overflow-hidden">
                {/* Toolbar */}
                <div className="flex items-center justify-between px-6 py-4 border-b border-surface-container">
                  <div className="flex items-center gap-4">
                    <span className="text-xs font-bold uppercase tracking-widest text-outline">v1.2 Draft</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <button type="button" onClick={() => copyDraft()} className="p-2 hover:bg-surface-container rounded-lg text-primary transition-colors" title="Copy">
                      <span className="material-symbols-outlined">content_copy</span>
                    </button>
                    <button type="button" onClick={() => downloadTxt()} className="flex items-center gap-2 px-3 py-2 hover:bg-surface-container rounded-lg text-primary transition-colors text-sm font-medium">
                      <span className="material-symbols-outlined text-[20px]">download</span> .txt
                    </button>
                    <button type="button" onClick={() => void exportPdf()} className="flex items-center gap-2 px-4 py-2 bg-primary text-on-primary rounded-lg transition-all hover:opacity-90 text-sm font-medium">
                      <span className="material-symbols-outlined text-[20px]">picture_as_pdf</span> PDF Export
                    </button>
                  </div>
                </div>

                {/* Paper */}
                <div
                  className="min-h-[600px] bg-slate-100 p-10 leading-loose [background-image:linear-gradient(to_bottom,transparent_31px,rgb(226_232_240)_32px)] [background-size:100%_32px] dark:bg-slate-950 dark:[background-image:linear-gradient(to_bottom,transparent_31px,rgb(51_65_85)_32px)]"
                >
                  <div className="mx-auto max-w-prose bg-white p-8 text-slate-900 shadow-sm dark:border dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100">
                    <div className="whitespace-pre-wrap text-sm leading-relaxed">
                      {draftLoading ? 'Generating drafts from your claim analysis…' : drafts[activeTab]}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Sidebar */}
            <div className="lg:col-span-4 space-y-8">
              {/* Assumptions & Gaps — POST /outputs/assumptions */}
              <section className="bg-surface-container-high p-6 rounded-xl">
                <div className="flex items-center justify-between gap-2 mb-3 flex-wrap">
                  <div className="flex items-center gap-2">
                    <span className="material-symbols-outlined text-primary">psychology</span>
                    <h3 className="font-headline font-bold text-lg text-primary">Assumptions &amp; Gaps</h3>
                  </div>
                  {assumptionsState.overall_confidence_percentage ? (
                    <span className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant">
                      Overall {assumptionsState.overall_confidence_percentage}
                    </span>
                  ) : null}
                </div>
                {assumptionsState.loading && (
                  <div className="space-y-3">
                    <div className="h-3 bg-surface-container rounded animate-pulse w-full" />
                    <div className="h-3 bg-surface-container rounded animate-pulse w-[90%]" />
                    <div className="h-16 bg-surface-container rounded animate-pulse w-full" />
                  </div>
                )}
                {!assumptionsState.loading && assumptionsState.error && (
                  <p className="text-sm text-error">{assumptionsState.error}</p>
                )}
                {!assumptionsState.loading && !assumptionsState.error && assumptionsState.reliability_note && (
                  <p className="text-xs text-on-surface-variant leading-relaxed mb-4 border-l-2 border-primary pl-3">
                    {assumptionsState.reliability_note}
                  </p>
                )}
                {!assumptionsState.loading && !assumptionsState.error && assumptionsState.items.length === 0 && (
                  <p className="text-sm text-on-surface-variant">
                    No assumptions were returned. Run <strong>/analyze</strong> so the model can record plan-type and deadline assumptions.
                  </p>
                )}
                {!assumptionsState.loading && !assumptionsState.error && assumptionsState.items.length > 0 && (
                  <ul className="space-y-4">
                    {assumptionsState.items.map((row, i) => (
                      <li key={`${row.assumption.slice(0, 48)}-${i}`} className="border border-outline-variant/20 rounded-lg p-3 bg-surface-container-lowest">
                        <div className="flex flex-wrap items-center gap-2 mb-1">
                          <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded ${impactBadgeClass(row.impact)}`}>
                            {row.impact} impact
                          </span>
                          <span className="text-[10px] font-bold text-on-surface-variant">{row.confidence_percentage}</span>
                        </div>
                        <p className="text-sm font-semibold text-on-surface mb-2">{row.assumption}</p>
                        <p className="text-xs text-on-surface-variant mb-1">
                          <span className="font-bold text-primary">Verify:</span> {row.how_to_verify}
                        </p>
                        <p className="text-xs text-on-surface-variant italic">
                          <span className="font-bold not-italic">If wrong:</span> {row.if_incorrect}
                        </p>
                      </li>
                    ))}
                  </ul>
                )}
              </section>

              {/* Action Plan */}
              <section className="bg-surface-container-low p-6 rounded-xl">
                <h3 className="font-headline font-bold text-lg text-primary mb-4">Action Plan</h3>
                <div className="space-y-3">
                  {items.map((item, i) => (
                    <label key={item.label} className="flex items-center gap-3 p-3 bg-surface-container-lowest rounded-lg border border-transparent hover:border-outline-variant/30 cursor-pointer transition-all">
                      <input
                        className="rounded-sm text-primary focus:ring-primary h-4 w-4"
                        type="checkbox"
                        checked={item.done}
                        onChange={() => setItems(items.map((it, idx) => idx === i ? { ...it, done: !it.done } : it))}
                      />
                      <span className={`text-sm font-medium ${item.done ? 'line-through text-on-surface-variant' : ''}`}>{item.label}</span>
                    </label>
                  ))}
                </div>
              </section>

              {/* Indiana Resources */}
              <section className="relative overflow-hidden rounded-xl bg-primary p-6 text-on-primary shadow-lg ring-1 ring-black/10 dark:!bg-slate-900 dark:!text-slate-100 dark:ring-sky-500/25">
                <div className="relative z-10">
                  <h3 className="mb-4 font-headline text-lg font-bold">State regulator (from analysis)</h3>
                  <div className="mb-6 space-y-4">
                    <div className="flex items-center gap-3">
                      <span className="material-symbols-outlined text-secondary-fixed dark:!text-sky-400">account_balance</span>
                      <span className="text-sm font-semibold dark:!text-slate-100">
                        {doiBlock?.name ?? 'Complete /analyze for DOI contact block'}
                      </span>
                    </div>
                    <div className="space-y-1 text-xs leading-relaxed opacity-90 dark:!text-slate-400">
                      {doiBlock?.address ? <p>{doiBlock.address}</p> : null}
                      {doiBlock?.phone ? <p className="pt-2">Phone: {doiBlock.phone}</p> : null}
                    </div>
                  </div>
                  <a
                    href={doiBlock?.website || 'https://www.in.gov/idoi/'}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex w-full items-center justify-center rounded-lg bg-on-primary px-4 py-3 text-sm font-bold text-primary transition-colors hover:bg-secondary-container dark:!border dark:!border-slate-600 dark:!bg-slate-800 dark:!text-slate-100 dark:hover:!bg-slate-700"
                  >
                    Open regulator site
                    <span className="material-symbols-outlined ml-2 text-[18px]">open_in_new</span>
                  </a>
                </div>
                <div className="absolute -bottom-4 -right-4 opacity-10">
                  <span className="material-symbols-outlined text-[120px]">gavel</span>
                </div>
              </section>
            </div>
          </div>
        </div>
      </main>

      <Footer disclaimer="Disclaimer: Resolvly is an advocacy platform and does not provide legal advice. All drafting tools should be reviewed by an attorney or qualified patient advocate before submission to insurers or the State of Indiana." />
    </div>
  )
}
